### ISSUE TITLE
Contribution email problem

### ISSUE THREAD

**Issue by reason-rock** [autowarefoundation/autoware-launch-gui#21]
![Screenshot1](https://github.com/user-attachments/assets/72a86dd8-00e0-413d-b941-e45ab45dc9a8)
![Screenshot2](https://github.com/user-attachments/assets/4ecf02ae-ce16-4397-9ba4-f3a1344757a3)
![Screenshot3](https://github.com/user-attachments/assets/81f93b30-781b-447f-9d2d-e1e753d778c3)

The email was misstated due to my ignorance. And I can't modify it because it's already merged.
If possible, I would like you to revise it.
I sent you an e-mail on August 1st for more information.

**Comment by KhalilSelyan** [comment]
Saw this, will be taking care of it first thing next monday I'm ooo this week.

**Comment by KhalilSelyan** [comment]
@reason-rock should be all good now

**Comment by KhalilSelyan** [comment]
@reason-rock should be all good now

**Comment by reason-rock** [comment]
Thank you so much!
