### ISSUE TITLE
Hope an arm64 .deb package

### ISSUE THREAD

**Issue by TangLongbin** [autowarefoundation/autoware-launch-gui#7]
# Description
I am using an arm64 platform computer to run autoware, and want to use **the gui**.
I only found amd64 deb package, which can not be installed on my computer.
So I downloaded the source code and built it locally, it can work but not convenient.
**Could you please build an arm64 version deb in the release?**

**Comment by KhalilSelyan** [comment]
Sure thing, I'll be adding that starting from v1.0.3

**Comment by TangLongbin** [comment]
Thanks!
